### ISSUE TITLE
hevea 2.32 not compile with ocaml 4.07.1 and ocamlbuild 0.13.0

### ISSUE THREAD

**Issue by perestoronin** [maranget/hevea#5] opened 2019-01-20 10:28 UTC
hevea 2.32 not compile with ocaml 4.07.1 and ocamlbuild 0.13.0

`sh ocb.sh opt
File "./check402.ml", line 1:
Error: Reference to undefined global `Stdlib__sys'`

`/usr/bin/ocamldep.opt -modules auxx.ml > auxx.ml.depends
/usr/bin/ocamldep.opt -modules misc.ml > misc.ml.depends
/usr/bin/ocamldep.opt -modules location.ml > location.ml.depends
/usr/bin/ocamldep.opt -modules myLexing.ml > myLexing.ml.depends
/usr/bin/ocamldep.opt -modules bytes.ml > bytes.ml.depends
/usr/bin/ocamldep.opt -modules bytes.mli > bytes.mli.depends
/usr/bin/ocamlc.opt -c -w +a-3-4-9-41-45 -annot -safe-string -o bytes.cmi bytes.mli
/usr/bin/ocamlopt.opt -c -w +a-3-4-9-41-45 -annot -safe-string -o bytes.cmx bytes.ml
+ /usr/bin/ocamlopt.opt -c -w +a-3-4-9-41-45 -annot -safe-string -o bytes.cmx bytes.ml
File "bytes.ml", line 1:
Error: The implementation bytes.ml does not match the interface bytes.cmi:
       Values do not match:
         val blit_string : string -> int -> bytes -> int -> int -> unit
       is not included in
         val blit_string : string -> int -> t -> int -> int -> unit
       File "bytes.mli", line 6, characters 0-58: Expected declaration
       File "bytes.ml", line 4, characters 4-15: Actual declaration`

Please help to fix !

**Comment by maranget** [comment] 2019-01-21 13:46
Hi,
I could not reproduce de problem.
Something may wrong with your installation. More especifically, what is the outcome of running ocaml ./check402.ml by hand ?

**Comment by perestoronin** [comment] 2019-01-21 14:01
`
ws /var/tmp/portage/dev-tex/hevea-2.32/work/hevea-2.32 # ocaml check402.ml
File "./check402.ml", line 1:
Error: Reference to undefined global `Stdlib__sys'`

**Comment by maranget** [comment] 2019-01-21 14:17
This outcome confirms my diagnostic: something is wrong with your ocaml installation.  You can also try '`ocaml -version`, it sould fail just as well.

I suspect that the library files of a previoulsy installed ocaml system are still here. If you have su rights on your machine, you can attempt deleting directory /usr/lib/ocaml (or, more cautiously, moving this directory to /usr/lib/ocaml.keep) and re-installing ocaml.

**Closed** 2020-03-25 09:29 UTC
